# Generated by Django 5.0.7 on 2025-04-15 10:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weightrecord',
            options={'ordering': ['-date'], 'verbose_name': '体重记录', 'verbose_name_plural': '体重记录'},
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='height',
            field=models.DecimalField(decimal_places=2, default=1.7, max_digits=3, verbose_name='身高(m)'),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='记录日期'),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='note',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='体重(kg)'),
        ),
    ]
